fix: error in autostart with backslash delimited paths
neovim/nvim-lspconfig pull request #1380
Opened 2021-11-07 03:25 UTC by adrianmgg

autocommands always want slash delimited paths, even on windows.

from `:help file-pattern` -
> ```
> Note that for all systems the '/' character is used for path separator (even
> Windows). This was done because the backslash is difficult to use in a pattern
> and to make the autocommands portable across different systems.
> ```

it seems like it usually works anyways and the autocommand will register fine despite its path containing backslashes, but there are a few cases where it will actually cause an error (and even if there weren't, it's still probably a good idea to format the path according to what the docs say)

in the case where i encountered the issue, i had a folder with a name that started with two underscores (`D:\__foo\`...), which caused this error:
```
E5108: Error executing lua ...ck\packer\start\nvim-lspconfig\configs.lua:84: Vim(autocmd):E877: (NFA regexp) Invalid character class: 95
```
, which was presumably due to the `_` character class expecting the character following it to be a valid character class. from `:help /character-classes` -
> ```
> Character classes:					*/character-classes*
>       magic   nomagic	matches 
> ...
> |/\_|	\_x	\_x	where x is any of the characters above: character
> 			class with end-of-line included
> ```

----

this PR fixes that issue, and adds a `normalize_for_autocmd(path)` function to `util.path` which replaces `\` with `/` in the path if on windows

2021-11-07 18:54 UTC, kylo252 requested changes
I think this should be enough since `root_dir` should already be normalized.

2021-11-07 18:54 UTC, kylo252 commented on lua/lspconfig/configs.lua
> +          'BufReadPost ' .. util.path.normalize_for_autocmd(root_dir) .. '/*',
```suggestion
          'BufReadPost ' .. util.path.join(root_dir, '*'),
```

2021-11-07 18:54 UTC, kylo252 commented on lua/lspconfig/util.lua
> +
```suggestion
 ```

2021-11-07 18:54 UTC, kylo252 commented on lua/lspconfig/util.lua
> +    normalize_for_autocmd = normalize_for_autocmd,
```suggestion
```

2021-11-07 22:52 UTC, adrianmgg commented
> I think this should be enough since `root_dir` should already be normalized.

the way the paths need to be normalized for autocommands specifically is to have forward slashes *regardless of* the os, the existing `util.path` functions are for more general path manipulation so they use an os-specific path separator
> ```lua
> local path_sep = is_windows and '\\' or '/'
> ```

as a test, i put in your suggested changes along with some debug prints right above where the command is run, then tested that with `/` and `\` delimited paths (using `set shellslash`)

```vim
e hello_world.py

set shellslash
LspStop
LspStart
" root_dir                        : D:/__temp/foo/hello_world.py
" util.path.normalize_for_autocmd : D:/__temp/foo/hello_world.py/*
" util.path.join (using this one) : D:/__temp/foo/hello_world.py\*

set noshellslash
LspStop
LspStart
" root_dir                        : D:\__temp\foo
" util.path.normalize_for_autocmd : D:/__temp/foo/*
" util.path.join (using this one) : D:\__temp\foo\*
" E5108: Error executing lua ...ck\packer\start\nvim-lspconfig\lua\lspconfig\configs.lua:80: Vim(autocmd):E877: (NFA regexp) Invalid character class: 95
```

as you can see, `util.path.join` (correctly) keeps `root_dir`'s `\`s as `\`s, which is usually what you would want but isn't correct when working with autocommands

(also, looking back at those paths from the test above it turns out there's a problem with multiple of the `util.path` functions assuming the input path will be exclusively `\` delimited on windows even though `/` is usually also valid, i'll create an issue for that)

2021-11-07 23:03 UTC, adrianmgg commented
also, spaces in the path need to be backslash escaped in an autocommand, `normalize_for_autocmd` should handle that as well

2021-11-08 02:06 UTC, adrianmgg commented
added a call to `fnameescape` to make the autocommand work with paths that contain spaces, renamed the new `util.path.normalize_for_autocmd` to `util.path.to_unix_style` since that's more descriptive of what it actually does

2021-11-08 07:57 UTC, kylo252 approved these changes

2021-11-16 04:15 UTC, mjlbach commented
let's lump in the capitalization of the drive letter and fnamescape into the function, and I'd prefer "normalize_path", I think we can reuse the normalization here for the internal logic to fix the issue with buf_add (see the other pr)

2021-12-22 09:49 UTC, mjlbach commented
Closing in favor of https://github.com/neovim/nvim-lspconfig/pull/1593

2021-12-22 09:49 UTC, closed without merging