docs: Arduino - Mention upstream keywords bug.
neovim/nvim-lspconfig pull request #2434
Opened 2023-02-04 10:47 UTC by doronbehar

BTW, perhaps the original contributor of this language server (@mjlbach) knows why does Arduino officially says that `sketch.json` is not used by `arduino-cli` and how is this file related to the language server. Although I don't know the answer to this question, I'm pretty sure this documentation suggestion is still relevant.

2023-02-04 11:21 UTC, glepnir commented on lua/lspconfig/server_configurations/arduino_language_server.lua
> +Note that an [upstream bug](https://github.com/arduino/arduino-ide/issues/159) makes keywords in some cases become undefined by the language server.
if you want people click or copy this link there is no need use markdown link syntax.

2023-02-05 01:55 UTC, glepnir requested changes
like i said no need markdown syntax for link

2023-02-05 10:01 UTC, doronbehar commented
> no need markdown syntax for link

I don't understand, the same text includes many links such as I wrote and they get compiled as expected to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#arduino_language_server .

2023-02-05 10:03 UTC, glepnir commented
if people use the treesitter markdown parse this link will hide.

2023-03-06 09:06 UTC, closed without merging